export const translations = {
  "關於我": "About me",
  "精選作品": "Selected work",
  "聯絡我": "Contact",
  "關閉": "Close",
  "選單": "Menu",
  "看看我的作品": "Explore my work",
  "多認識我一點": "More about me",
  "不只是一段自我介紹。": "More than an introduction.",
  "在資訊與區塊鏈之間，持續探索與實作。": "Exploring and building at the intersection of information technology and blockchain.",
  "一些想法，一些實踐。": "Ideas put into practice.",
  "公開專案 / GitHub": "Public projects / GitHub",
  "下一個好點子，或許從一句嗨開始。": "The next great idea could start with a hello.",
  "聊聊合作、交流想法，或只是打聲招呼。": "Let’s collaborate, exchange ideas, or simply say hello.",
  "寄信給我": "Email me",
  "在 GitHub 查看專案": "View project on GitHub",
  "回到頂端": "Back to top",
  "金融資料應用": "Financial data application",
  "畢業專題": "Graduation project",
  "前端專案": "Frontend project",
  "前端開發": "Frontend development",
  "台股基本面估價與互動式 K 線分析。": "Taiwan stock valuation and interactive candlestick analysis.",
  "畢業專題・負責前端開發。": "Graduation project · Responsible for frontend development.",
  "負責前端開發。": "Responsible for frontend development.",
  "我在 ProfiqAI 專案中負責前端開發。": "I was responsible for frontend development on ProfiqAI.",
  "我在 GasPass 專案中負責前端開發。": "I was responsible for frontend development on GasPass.",
  "結合基本面估價與技術面分析的台股儀表板，支援上市、上櫃股票代碼與中文名稱搜尋。以 DCF、P/E 模型整合合理價，搭配安全邊際、支撐壓力位與互動式 K 線圖，整理研究所需的資訊。": "A Taiwan stock dashboard combining fundamental valuation and technical analysis. It supports listed and OTC stock searches by ticker or Chinese name, combining DCF and P/E valuations with margins of safety, support and resistance levels, and interactive candlestick charts.",
  "Vue 3、Tailwind CSS 與 Lightweight Charts 呈現分析介面。": "The analysis interface uses Vue 3, Tailwind CSS, and Lightweight Charts.",
  "FastAPI 搭配 yfinance、Pandas 與 NumPy 處理資料與估價計算。": "FastAPI, yfinance, Pandas, and NumPy handle data processing and valuation calculations.",
  "研究與作品展示用途，不構成投資建議。": "For research and portfolio demonstration only. Not investment advice.",
  "區塊鏈黑客松": "Blockchain hackathons",
  "團隊協作": "Team collaboration",
  "潘永澔": "PAN, YUNG-HAO",
  "資訊與財金背景的研究生，專注探索 Web3、區塊鏈與 AI Agent，透過專題與黑客松累積實作經驗。": "A graduate student in Information and Finance Management, exploring Web3, blockchain, and AI agents through projects and hackathons.",
  "我畢業於國立臺北科技大學資訊與財金管理系，目前為該系所研究生。我重視效率與責任，熱衷學習新技術，並樂於與團隊共同解決問題。": "I earned my bachelor’s degree in Information and Finance Management at National Taipei University of Technology and am currently a graduate student in the same department. I value efficiency and responsibility, enjoy learning new technologies, and thrive on solving problems with a team.",
  "我對 Web3 技術充滿熱忱，持續探索去中心化金融（DeFi），並積極參與區塊鏈黑客松，透過實作深化對區塊鏈應用的理解。具備 Python 與 Solidity 基礎，也在課程、專題及團隊專案中累積程式應用與前端開發經驗。": "I am passionate about Web3, actively exploring decentralized finance (DeFi) and competing in blockchain hackathons to deepen my practical understanding of blockchain applications. With foundational knowledge of Python and Solidity, I have gained programming and frontend development experience through coursework, projects, and team collaboration.",
  "目前正探索 AI Agent 與區塊鏈系統的整合，並將其作為未來研究的核心方向；除了應用開發，也關注技術隱憂，尤其是 Agent Payment 中的交易安全問題。": "I am currently exploring the integration of AI agents with blockchain systems as the core of my future research. Beyond application development, I aim to investigate potential technical risks, particularly transaction security in agent payments.",
  "過往的股票投資與市場研究經驗，讓我持續關注金融需求如何與資訊技術結合。": "My experience in stock investing and market research keeps me interested in how information technology can address financial needs.",
  "未來希望透過南洋理工大學（NTU）的研究所課程，進一步深化區塊鏈應用的實作能力，並將研究想法轉化為具體成果。": "I aspire to further develop my practical skills in blockchain applications through postgraduate study at Nanyang Technological University (NTU), turning research ideas into tangible outcomes."
}
export const biography = [
  "我畢業於國立臺北科技大學資訊與財金管理系，目前為該系所研究生。我重視效率與責任，熱衷學習新技術，並樂於與團隊共同解決問題。",
  "我對 Web3 技術充滿熱忱，持續探索去中心化金融（DeFi），並積極參與區塊鏈黑客松，透過實作深化對區塊鏈應用的理解。具備 Python 與 Solidity 基礎，也在課程、專題及團隊專案中累積程式應用與前端開發經驗。",
  "目前正探索 AI Agent 與區塊鏈系統的整合，並將其作為未來研究的核心方向；除了應用開發，也關注技術隱憂，尤其是 Agent Payment 中的交易安全問題。",
  "過往的股票投資與市場研究經驗，讓我持續關注金融需求如何與資訊技術結合。",
  "未來希望透過南洋理工大學（NTU）的研究所課程，進一步深化區塊鏈應用的實作能力，並將研究想法轉化為具體成果。"
]
